apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-touch-app
  labels:
    app: zero-touch-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zero-touch-app
  template:
    metadata:
      labels:
        app: zero-touch-app
    spec:
      containers:
      - name: zero-touch-app
        image: zero:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
